version: '3.9'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: magistracy_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - magistracy-data:/var/lib/postgresql/data
    ports:
      - "5438:5432"

  auth:
    image: auth_v_1_0:latest
    build:
      context: authorization
      dockerfile: authorization/Dockerfile
    ports:
      - "8001:8001"

  user:
    image: user_v_0_0:latest
    build:
      context: user
      dockerfile: user/Dockerfile
    ports:
      - "8002:8002"

volumes:
  magistracy-data:
